var hierarchy =
[
    [ "com.tuya.smart.sdk.enums.ActivatorAPStepCode", "classcom_1_1tuya_1_1smart_1_1sdk_1_1enums_1_1_activator_a_p_step_code.html", null ],
    [ "com.tuya.smart.home.sdk.builder.ActivatorBuilder", "classcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1builder_1_1_activator_builder.html", null ],
    [ "com.tuya.smart.sdk.enums.ActivatorEZStepCode", "classcom_1_1tuya_1_1smart_1_1sdk_1_1enums_1_1_activator_e_z_step_code.html", null ],
    [ "com.tuya.smart.sdk.enums.ActivatorMeshStepCode", "classcom_1_1tuya_1_1smart_1_1sdk_1_1enums_1_1_activator_mesh_step_code.html", null ],
    [ "com.tuya.smart.sdk.enums.ActivatorModelEnum", "enumcom_1_1tuya_1_1smart_1_1sdk_1_1enums_1_1_activator_model_enum.html", null ],
    [ "com.tuya.smart.home.sdk.bean.ActiveDmDeviceBean", "classcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1bean_1_1_active_dm_device_bean.html", null ],
    [ "com.tuya.smart.sdk.api.wifibackup.api.bean.BackupWifiBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1wifibackup_1_1api_1_1bean_1_1_backup_wifi_bean.html", null ],
    [ "com.tuya.smart.sdk.api.wifibackup.api.bean.BaseInfo", "classcom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1wifibackup_1_1api_1_1bean_1_1_base_info.html", [
      [ "com.tuya.smart.sdk.api.wifibackup.api.bean.BackupWifiListInfo", "classcom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1wifibackup_1_1api_1_1bean_1_1_backup_wifi_list_info.html", null ],
      [ "com.tuya.smart.sdk.api.wifibackup.api.bean.BackupWifiResultBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1wifibackup_1_1api_1_1bean_1_1_backup_wifi_result_bean.html", null ],
      [ "com.tuya.smart.sdk.api.wifibackup.api.bean.CurrentWifiInfoBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1wifibackup_1_1api_1_1bean_1_1_current_wifi_info_bean.html", null ],
      [ "com.tuya.smart.sdk.api.wifibackup.api.bean.SwitchWifiResultBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1wifibackup_1_1api_1_1bean_1_1_switch_wifi_result_bean.html", null ]
    ] ],
    [ "com.tuya.smart.sdk.bean.BleActivatorBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_ble_activator_bean.html", null ],
    [ "com.tuya.smart.android.ble.api.BleConfigType", "enumcom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_ble_config_type.html", null ],
    [ "com.tuya.smart.android.ble.builder.BleConnectBuilder", "classcom_1_1tuya_1_1smart_1_1android_1_1ble_1_1builder_1_1_ble_connect_builder.html", null ],
    [ "com.tuya.smart.android.ble.api.BleConnectStatusListener", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_ble_connect_status_listener.html", null ],
    [ "com.tuya.smart.android.ble.api.BleControllerBean", "classcom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_ble_controller_bean.html", null ],
    [ "com.tuya.smart.android.ble.api.BleControllerUpdateBean", "classcom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_ble_controller_update_bean.html", null ],
    [ "com.tuya.smart.android.ble.api.BleLogCallback", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_ble_log_callback.html", null ],
    [ "com.tuya.smart.android.ble.api.BleRssiListener", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_ble_rssi_listener.html", null ],
    [ "com.tuya.smart.android.blemesh.bean.BLEUpgradeInfoBean", "classcom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1bean_1_1_b_l_e_upgrade_info_bean.html", null ],
    [ "com.tuya.smart.android.ble.api.BleWiFiDeviceBean", "classcom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_ble_wi_fi_device_bean.html", null ],
    [ "com.tuya.smart.sdk.bean.BlueMeshGroupBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_blue_mesh_group_bean.html", null ],
    [ "com.tuya.smart.sdk.bean.BlueMeshModuleMapBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_blue_mesh_module_map_bean.html", null ],
    [ "com.tuya.smart.sdk.bean.BlueMeshRelationDevBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_blue_mesh_relation_dev_bean.html", null ],
    [ "com.tuya.smart.sdk.bean.BlueMeshRoomBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_blue_mesh_room_bean.html", null ],
    [ "com.tuya.smart.sdk.bean.BlueMeshShareBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_blue_mesh_share_bean.html", null ],
    [ "com.tuya.smart.sdk.bean.BlueMeshSubDevBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_blue_mesh_sub_dev_bean.html", null ],
    [ "com.tuya.smart.sdk.bean.BlueMeshWifiStatusBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_blue_mesh_wifi_status_bean.html", null ],
    [ "com.tuya.smart.android.ble.api.BluetoothStateChangedListener", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_bluetooth_state_changed_listener.html", null ],
    [ "com.tuya.smart.sdk.bean.BluetoothStatusBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_bluetooth_status_bean.html", null ],
    [ "com.tuya.smart.android.device.builder.TuyaTimerBuilder.Builder", "classcom_1_1tuya_1_1smart_1_1android_1_1device_1_1builder_1_1_tuya_timer_builder_1_1_builder.html", null ],
    [ "com.tuya.smart.android.ble.api.LeScanSetting.Builder", "classcom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_le_scan_setting_1_1_builder.html", null ],
    [ "com.tuya.smart.android.ble.api.ThirdBleScanDeviceBuilder.Builder", "classcom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_third_ble_scan_device_builder_1_1_builder.html", null ],
    [ "com.tuya.smart.android.blemesh.api.BusinessResultListener< T, F >", "interfacecom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1api_1_1_business_result_listener.html", null ],
    [ "com.tuya.smart.android.camera.api.bean.CameraPushDataBean", "classcom_1_1tuya_1_1smart_1_1android_1_1camera_1_1api_1_1bean_1_1_camera_push_data_bean.html", null ],
    [ "Cloneable", null, [
      [ "com.tuya.smart.android.user.bean.Domain", "classcom_1_1tuya_1_1smart_1_1android_1_1user_1_1bean_1_1_domain.html", null ],
      [ "com.tuya.smart.android.user.bean.User", "classcom_1_1tuya_1_1smart_1_1android_1_1user_1_1bean_1_1_user.html", null ],
      [ "com.tuya.smart.android.user.bean.UserToB", "classcom_1_1tuya_1_1smart_1_1android_1_1user_1_1bean_1_1_user_to_b.html", null ]
    ] ],
    [ "com.tuya.smart.sdk.bean.CloudZigbeeGroupCreateBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_cloud_zigbee_group_create_bean.html", null ],
    [ "com.tuya.smart.android.user.bean.CommonConfigBean", "classcom_1_1tuya_1_1smart_1_1android_1_1user_1_1bean_1_1_common_config_bean.html", null ],
    [ "com.tuya.smart.android.ble.api.ConfigErrorBean", "classcom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_config_error_bean.html", null ],
    [ "com.tuya.smart.android.config.bean.ConfigErrorRespBean", "classcom_1_1tuya_1_1smart_1_1android_1_1config_1_1bean_1_1_config_error_resp_bean.html", null ],
    [ "com.tuya.smart.home.sdk.bean.ConfigProductInfoBean", "classcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1bean_1_1_config_product_info_bean.html", null ],
    [ "com.tuya.smart.android.ble.api.DataChannelListener", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_data_channel_listener.html", [
      [ "com.tuya.smart.android.ble.api.DataCustomChannelListener", "classcom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_data_custom_channel_listener.html", null ]
    ] ],
    [ "com.tuya.smart.android.device.bean.DataPointBean", "classcom_1_1tuya_1_1smart_1_1android_1_1device_1_1bean_1_1_data_point_bean.html", null ],
    [ "com.tuya.smart.android.device.bean.DataPointStatBean", "classcom_1_1tuya_1_1smart_1_1android_1_1device_1_1bean_1_1_data_point_stat_bean.html", null ],
    [ "com.tuya.smart.android.device.enums.DataPointTypeEnum", "enumcom_1_1tuya_1_1smart_1_1android_1_1device_1_1enums_1_1_data_point_type_enum.html", null ],
    [ "com.tuya.smart.android.device.enums.DataTypeEnum", "enumcom_1_1tuya_1_1smart_1_1android_1_1device_1_1enums_1_1_data_type_enum.html", null ],
    [ "com.tuya.smart.sdk.enums.DeviceActiveEnum", "enumcom_1_1tuya_1_1smart_1_1sdk_1_1enums_1_1_device_active_enum.html", null ],
    [ "com.tuya.smart.sdk.bean.DeviceBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_device_bean.html", null ],
    [ "com.tuya.smart.home.sdk.bean.DeviceBizPropBean", "classcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1bean_1_1_device_biz_prop_bean.html", null ],
    [ "com.tuya.smart.android.device.bean.DeviceInfoBean", "classcom_1_1tuya_1_1smart_1_1android_1_1device_1_1bean_1_1_device_info_bean.html", null ],
    [ "com.tuya.smart.home.sdk.bean.DeviceType", "enumcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1bean_1_1_device_type.html", null ],
    [ "com.tuya.smart.android.ble.api.DevIotDataBean", "classcom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_dev_iot_data_bean.html", null ],
    [ "com.tuya.smart.sdk.bean.cache.IDeviceProperty.DevUpgradeStatus", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1cache_1_1_i_device_property_1_1_dev_upgrade_status.html", null ],
    [ "com.tuya.smart.sdk.bean.DpBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_dp_bean.html", null ],
    [ "com.tuya.smart.android.blemesh.bean.DpsParseBean", "classcom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1bean_1_1_dps_parse_bean.html", null ],
    [ "com.tuya.smart.sdk.api.cache.ISmartCacheManager.Entity", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1cache_1_1_i_smart_cache_manager_1_1_entity.html", null ],
    [ "com.tuya.smart.home.sdk.bean.EnvBean", "classcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1bean_1_1_env_bean.html", null ],
    [ "com.tuya.smart.android.ble.builder.BleConnectBuilder.ExtInfo", "classcom_1_1tuya_1_1smart_1_1android_1_1ble_1_1builder_1_1_ble_connect_builder_1_1_ext_info.html", null ],
    [ "com.tuya.smart.sdk.bean.push.TuyaPushBean.NotificationBean.ExtraBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1push_1_1_tuya_push_bean_1_1_notification_bean_1_1_extra_bean.html", null ],
    [ "com.tuya.smart.sdk.bean.ProductStandardConfig.FunctionSchemaBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_product_standard_config_1_1_function_schema_bean.html", null ],
    [ "com.tuya.smart.sdk.bean.StandSchema.FunctionSchemaListBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_stand_schema_1_1_function_schema_list_bean.html", null ],
    [ "com.tuya.smart.sdk.bean.GroupBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_group_bean.html", null ],
    [ "com.tuya.smart.home.sdk.builder.GroupCreateBuilder", "classcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1builder_1_1_group_create_builder.html", null ],
    [ "com.tuya.smart.sdk.bean.GroupDeviceBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_group_device_bean.html", null ],
    [ "com.tuya.smart.android.device.bean.GroupDeviceRespBean", "classcom_1_1tuya_1_1smart_1_1android_1_1device_1_1bean_1_1_group_device_resp_bean.html", null ],
    [ "com.tuya.smart.android.device.bean.HardwareUpgradeBean", "classcom_1_1tuya_1_1smart_1_1android_1_1device_1_1bean_1_1_hardware_upgrade_bean.html", null ],
    [ "com.tuya.smart.home.sdk.api.IActivator", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1api_1_1_i_activator.html", null ],
    [ "com.tuya.smart.sdk.api.bluemesh.IAddGroupCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_add_group_callback.html", null ],
    [ "com.tuya.smart.sdk.api.bluemesh.IAddRoomCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_add_room_callback.html", null ],
    [ "com.tuya.smart.sdk.api.bluemesh.IAddSubDevCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_add_sub_dev_callback.html", null ],
    [ "com.tuya.smart.home.sdk.api.config.IApConnectListener", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1api_1_1config_1_1_i_ap_connect_listener.html", null ],
    [ "com.tuya.smart.home.sdk.api.config.IBaseConnectListener", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1api_1_1config_1_1_i_base_connect_listener.html", null ],
    [ "com.tuya.smart.android.user.api.IBaseUser", "interfacecom_1_1tuya_1_1smart_1_1android_1_1user_1_1api_1_1_i_base_user.html", null ],
    [ "com.tuya.smart.sdk.api.IBleActivator", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_ble_activator.html", null ],
    [ "com.tuya.smart.sdk.api.IBleActivatorListener", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_ble_activator_listener.html", null ],
    [ "com.tuya.smart.sdk.api.bluemesh.IBlueMeshActivatorListener", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_blue_mesh_activator_listener.html", null ],
    [ "com.tuya.smart.sdk.api.bluemesh.IBlueMeshCreateCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_blue_mesh_create_callback.html", null ],
    [ "com.tuya.smart.sdk.api.bluemesh.IBlueMeshManager", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_blue_mesh_manager.html", null ],
    [ "com.tuya.smart.sdk.bean.cache.IBlueMeshProperty", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1cache_1_1_i_blue_mesh_property.html", [
      [ "com.tuya.smart.sdk.bean.cache.ISigMeshProperty", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1cache_1_1_i_sig_mesh_property.html", null ]
    ] ],
    [ "com.tuya.smart.android.user.api.IBooleanCallback", "interfacecom_1_1tuya_1_1smart_1_1android_1_1user_1_1api_1_1_i_boolean_callback.html", null ],
    [ "com.tuya.smart.android.user.api.ICommonConfigCallback", "interfacecom_1_1tuya_1_1smart_1_1android_1_1user_1_1api_1_1_i_common_config_callback.html", null ],
    [ "com.tuya.smart.home.sdk.api.config.IConfig", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1api_1_1config_1_1_i_config.html", null ],
    [ "com.tuya.smart.home.sdk.api.config.IConnectListener", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1api_1_1config_1_1_i_connect_listener.html", null ],
    [ "com.tuya.smart.sdk.api.IDeviceListener", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_device_listener.html", null ],
    [ "com.tuya.smart.sdk.bean.cache.IDeviceProperty", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1cache_1_1_i_device_property.html", null ],
    [ "com.tuya.smart.sdk.api.IDevListener", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_dev_listener.html", null ],
    [ "com.tuya.smart.home.sdk.api.IDevModel", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1api_1_1_i_dev_model.html", null ],
    [ "com.tuya.smart.sdk.api.IGetAllTimerWithDevIdCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_get_all_timer_with_dev_id_callback.html", null ],
    [ "com.tuya.smart.android.device.api.IGetDataPointStatCallback", "interfacecom_1_1tuya_1_1smart_1_1android_1_1device_1_1api_1_1_i_get_data_point_stat_callback.html", null ],
    [ "com.tuya.smart.sdk.api.IGetDevicesInGroupCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_get_devices_in_group_callback.html", null ],
    [ "com.tuya.smart.sdk.api.IGetDeviceTimerStatusCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_get_device_timer_status_callback.html", null ],
    [ "com.tuya.smart.sdk.api.IGetDevsFromGroupByPidCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_get_devs_from_group_by_pid_callback.html", null ],
    [ "com.tuya.smart.sdk.api.IGetGroupAlarmCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_get_group_alarm_callback.html", null ],
    [ "com.tuya.smart.sdk.api.bluemesh.IGetGroupAndDevListCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_get_group_and_dev_list_callback.html", null ],
    [ "com.tuya.smart.sdk.api.bluemesh.IGetMeshRoomAndGroupListCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_get_mesh_room_and_group_list_callback.html", null ],
    [ "com.tuya.smart.sdk.api.IGetOtaInfoCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_get_ota_info_callback.html", null ],
    [ "com.tuya.smart.android.user.api.IGetRegionCallback", "interfacecom_1_1tuya_1_1smart_1_1android_1_1user_1_1api_1_1_i_get_region_callback.html", null ],
    [ "com.tuya.smart.sdk.api.IGetSubDevListCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_get_sub_dev_list_callback.html", null ],
    [ "com.tuya.smart.sdk.api.IGetTimerWithTaskCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_get_timer_with_task_callback.html", null ],
    [ "com.tuya.smart.sdk.api.bluemesh.IGroupDevCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_group_dev_callback.html", null ],
    [ "com.tuya.smart.sdk.api.IGroupListener", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_group_listener.html", null ],
    [ "com.tuya.smart.sdk.bean.cache.IGroupProperty", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1cache_1_1_i_group_property.html", null ],
    [ "com.tuya.smart.home.sdk.api.config.IGwConfigListener", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1api_1_1config_1_1_i_gw_config_listener.html", null ],
    [ "com.tuya.smart.home.sdk.api.IGwSearchListener", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1api_1_1_i_gw_search_listener.html", null ],
    [ "com.tuya.smart.android.blemesh.callback.ILocalQueryGroupDevCallback", "interfacecom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1callback_1_1_i_local_query_group_dev_callback.html", null ],
    [ "com.tuya.smart.android.user.api.ILogoutCallback", "interfacecom_1_1tuya_1_1smart_1_1android_1_1user_1_1api_1_1_i_logout_callback.html", null ],
    [ "com.tuya.smart.sdk.api.bluemesh.IMeshDeviceListener", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_mesh_device_listener.html", null ],
    [ "com.tuya.smart.sdk.api.bluemesh.IMeshDevListener", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_mesh_dev_listener.html", [
      [ "com.tuya.smart.sdk.api.bluemesh.IMeshDevListenerV2", "classcom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_mesh_dev_listener_v2.html", null ]
    ] ],
    [ "com.tuya.smart.sdk.api.bluemesh.IMeshStatusListener", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_mesh_status_listener.html", null ],
    [ "com.tuya.smart.sdk.api.IMultiModeActivator", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_multi_mode_activator.html", null ],
    [ "com.tuya.smart.sdk.api.IMultiModeActivatorListener", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_multi_mode_activator_listener.html", null ],
    [ "com.tuya.smart.sdk.api.INeedLoginListener", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_need_login_listener.html", null ],
    [ "com.tuya.smart.sdk.api.IOtaListener", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_ota_listener.html", null ],
    [ "com.tuya.smart.android.device.api.IPropertyCallback< T >", "interfacecom_1_1tuya_1_1smart_1_1android_1_1device_1_1api_1_1_i_property_callback.html", null ],
    [ "com.tuya.smart.android.user.api.IQurryDomainCallback", "interfacecom_1_1tuya_1_1smart_1_1android_1_1user_1_1api_1_1_i_qurry_domain_callback.html", null ],
    [ "com.tuya.smart.sdk.api.IRequestCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_request_callback.html", null ],
    [ "com.tuya.smart.sdk.api.bluemesh.IRequestMeshListCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_request_mesh_list_callback.html", null ],
    [ "com.tuya.smart.sdk.api.bluemesh.IRequestSigMeshListCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_request_sig_mesh_list_callback.html", null ],
    [ "com.tuya.smart.sdk.api.bluemesh.IRequestUpgradeInfoCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_request_upgrade_info_callback.html", null ],
    [ "com.tuya.smart.sdk.api.IResultCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_result_callback.html", null ],
    [ "com.tuya.smart.sdk.api.IResultStatusCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_result_status_callback.html", null ],
    [ "com.tuya.smart.sdk.api.bluemesh.ISigMeshCreateCallback", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_sig_mesh_create_callback.html", null ],
    [ "com.tuya.smart.sdk.api.bluemesh.ISigMeshManager", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_sig_mesh_manager.html", null ],
    [ "com.tuya.smart.sdk.api.cache.ISmartCacheManager", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1cache_1_1_i_smart_cache_manager.html", null ],
    [ "com.tuya.smart.sdk.api.cache.ISmartStatusChangeListener< T >", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1cache_1_1_i_smart_status_change_listener.html", null ],
    [ "com.tuya.smart.sdk.api.cache.ISmartStatusManager", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1cache_1_1_i_smart_status_manager.html", null ],
    [ "com.tuya.smart.sdk.api.IStandardConverter", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_standard_converter.html", null ],
    [ "com.tuya.smart.sdk.api.IStorageCache", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_storage_cache.html", [
      [ "com.tuya.smart.sdk.bean.BlueMeshBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_blue_mesh_bean.html", [
        [ "com.tuya.smart.sdk.bean.SigMeshBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_sig_mesh_bean.html", null ]
      ] ],
      [ "com.tuya.smart.sdk.bean.ProductBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_product_bean.html", null ]
    ] ],
    [ "com.tuya.smart.sdk.api.ISubDevListener", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_sub_dev_listener.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaActivator", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_activator.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaActivatorCreateToken", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_activator_create_token.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaActivatorGetToken", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_activator_get_token.html", null ],
    [ "com.tuya.smart.android.ble.ITuyaBeaconManager", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1_i_tuya_beacon_manager.html", null ],
    [ "com.tuya.smart.android.ble.api.ITuyaBleConfigListener", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_i_tuya_ble_config_listener.html", null ],
    [ "com.tuya.smart.android.ble.ITuyaBleController", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1_i_tuya_ble_controller.html", null ],
    [ "com.tuya.smart.android.ble.ITuyaBleManager", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1_i_tuya_ble_manager.html", null ],
    [ "com.tuya.smart.android.ble.ITuyaBleOperator", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1_i_tuya_ble_operator.html", null ],
    [ "com.tuya.smart.sdk.api.bluemesh.ITuyaBlueMesh", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_tuya_blue_mesh.html", [
      [ "com.tuya.smart.android.blemesh.api.ITuyaBlueMeshDevice", "interfacecom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1api_1_1_i_tuya_blue_mesh_device.html", null ]
    ] ],
    [ "com.tuya.smart.sdk.api.bluemesh.ITuyaBlueMeshActivator", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_tuya_blue_mesh_activator.html", null ],
    [ "com.tuya.smart.android.blemesh.api.ITuyaBlueMeshActivatorListener", "interfacecom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1api_1_1_i_tuya_blue_mesh_activator_listener.html", null ],
    [ "com.tuya.smart.android.blemesh.api.ITuyaBlueMeshBusiness< R >", "interfacecom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1api_1_1_i_tuya_blue_mesh_business.html", null ],
    [ "com.tuya.smart.android.blemesh.api.ITuyaBlueMeshClient", "interfacecom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1api_1_1_i_tuya_blue_mesh_client.html", null ],
    [ "com.tuya.smart.android.blemesh.api.ITuyaBlueMeshConfig", "interfacecom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1api_1_1_i_tuya_blue_mesh_config.html", null ],
    [ "com.tuya.smart.android.blemesh.api.ITuyaBlueMeshInit", "interfacecom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1api_1_1_i_tuya_blue_mesh_init.html", null ],
    [ "com.tuya.smart.android.blemesh.api.ITuyaBlueMeshOta", "interfacecom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1api_1_1_i_tuya_blue_mesh_ota.html", null ],
    [ "com.tuya.smart.android.blemesh.api.ITuyaBlueMeshSearch", "interfacecom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1api_1_1_i_tuya_blue_mesh_search.html", null ],
    [ "com.tuya.smart.android.blemesh.api.ITuyaBlueMeshSearchListener", "interfacecom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1api_1_1_i_tuya_blue_mesh_search_listener.html", null ],
    [ "com.tuya.smart.android.ble.api.ITuyaBluetoothFlow", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_i_tuya_bluetooth_flow.html", null ],
    [ "com.tuya.smart.sdk.api.cache.ITuyaCachePlugin", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1cache_1_1_i_tuya_cache_plugin.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaCameraDevActivator", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_camera_dev_activator.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaCommonTimer", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_common_timer.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaDataCallback< T >", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_data_callback.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaDevActivatorListener", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_dev_activator_listener.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaDevice", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_device.html", null ],
    [ "com.tuya.smart.home.sdk.api.ITuyaDeviceActivator", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1api_1_1_i_tuya_device_activator.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaDeviceBizPropBeanListManager", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_device_biz_prop_bean_list_manager.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaDeviceListManager", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_device_list_manager.html", null ],
    [ "com.tuya.smart.home.sdk.callback.ITuyaDeviceUpgradeStatusCallback", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1callback_1_1_i_tuya_device_upgrade_status_callback.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaGateway", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_gateway.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaGetBeanCallback< T >", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_get_bean_callback.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaGroup", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_group.html", [
      [ "com.tuya.smart.android.blemesh.api.ITuyaBlueMeshGroup", "interfacecom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1api_1_1_i_tuya_blue_mesh_group.html", null ]
    ] ],
    [ "com.tuya.smart.home.sdk.api.ITuyaGroupModel", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1api_1_1_i_tuya_group_model.html", null ],
    [ "com.tuya.smart.home.sdk.api.ITuyaGwActivator", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1api_1_1_i_tuya_gw_activator.html", null ],
    [ "com.tuya.smart.home.sdk.api.ITuyaGwSearcher", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1api_1_1_i_tuya_gw_searcher.html", null ],
    [ "com.tuya.smart.android.camera.api.ITuyaHomeCamera", "interfacecom_1_1tuya_1_1smart_1_1android_1_1camera_1_1api_1_1_i_tuya_home_camera.html", null ],
    [ "com.tuya.smart.home.sdk.api.ITuyaLightningActivator", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1api_1_1_i_tuya_lightning_activator.html", null ],
    [ "com.tuya.smart.home.sdk.api.ITuyaLightningSearcher", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1api_1_1_i_tuya_lightning_searcher.html", null ],
    [ "com.tuya.smart.home.sdk.api.ITuyaLightningSearchListener", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1api_1_1_i_tuya_lightning_search_listener.html", null ],
    [ "com.tuya.smart.sdk.api.bluemesh.ITuyaMeshGroup", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_tuya_mesh_group.html", null ],
    [ "com.tuya.smart.android.blemesh.ITuyaMeshService", "interfacecom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1_i_tuya_mesh_service.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaOta", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_ota.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaOtaPlugin", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_ota_plugin.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaQRCodeDevActivator", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_q_r_code_dev_activator.html", null ],
    [ "com.tuya.smart.home.sdk.callback.ITuyaResultCallback< T >", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1callback_1_1_i_tuya_result_callback.html", null ],
    [ "com.tuya.smart.sdk.api.bluemesh.ITuyaRoomManager", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1bluemesh_1_1_i_tuya_room_manager.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaSearchDeviceListener", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_search_device_listener.html", null ],
    [ "com.tuya.smart.home.sdk.api.ITuyaServer", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1api_1_1_i_tuya_server.html", null ],
    [ "com.tuya.smart.android.blemesh.api.ITuyaSigMeshClient", "interfacecom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1api_1_1_i_tuya_sig_mesh_client.html", null ],
    [ "com.tuya.smart.home.sdk.callback.ITuyaSingleTransfer", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1callback_1_1_i_tuya_single_transfer.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaSmartActivatorListener", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_smart_activator_listener.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaSmartCameraActivatorListener", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_smart_camera_activator_listener.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaSmartQRCodeActivatorListener", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_smart_q_r_code_activator_listener.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaSmartRequest", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_smart_request.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaSmartTimer", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_smart_timer.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaTimer", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_timer.html", null ],
    [ "com.tuya.smart.home.sdk.callback.ITuyaTransferCallback", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1callback_1_1_i_tuya_transfer_callback.html", null ],
    [ "com.tuya.smart.home.sdk.callback.ITuyaVoiceTransfer", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1callback_1_1_i_tuya_voice_transfer.html", null ],
    [ "com.tuya.smart.sdk.api.wifibackup.api.ITuyaWifiBase", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1wifibackup_1_1api_1_1_i_tuya_wifi_base.html", [
      [ "com.tuya.smart.sdk.api.wifibackup.api.ITuyaWifiBackup", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1wifibackup_1_1api_1_1_i_tuya_wifi_backup.html", null ],
      [ "com.tuya.smart.sdk.api.wifibackup.api.ITuyaWifiSwitch", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1wifibackup_1_1api_1_1_i_tuya_wifi_switch.html", null ]
    ] ],
    [ "com.tuya.smart.sdk.api.ITuyaWifiGroup", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_wifi_group.html", null ],
    [ "com.tuya.smart.sdk.api.ITuyaZigbeeGroup", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_i_tuya_zigbee_group.html", null ],
    [ "com.tuya.smart.android.user.api.IUserStorage", "interfacecom_1_1tuya_1_1smart_1_1android_1_1user_1_1api_1_1_i_user_storage.html", null ],
    [ "com.tuya.smart.home.sdk.api.IWarningMsgListener", "interfacecom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1api_1_1_i_warning_msg_listener.html", null ],
    [ "com.tuya.smart.android.ble.api.LeConnectResponse", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_le_connect_response.html", null ],
    [ "com.tuya.smart.android.ble.api.LeConnectStatusResponse", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_le_connect_status_response.html", null ],
    [ "com.tuya.smart.android.ble.api.LeScanSetting", "classcom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_le_scan_setting.html", null ],
    [ "com.tuya.smart.android.ble.builder.BleConnectBuilder.Level", "enumcom_1_1tuya_1_1smart_1_1android_1_1ble_1_1builder_1_1_ble_connect_builder_1_1_level.html", null ],
    [ "com.tuya.smart.home.sdk.bean.LightningSearchBean", "classcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1bean_1_1_lightning_search_bean.html", null ],
    [ "com.tuya.smart.android.blemesh.bean.MeshClientStatusEnum", "enumcom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1bean_1_1_mesh_client_status_enum.html", null ],
    [ "com.tuya.smart.android.blemesh.bean.MeshLogUploadDataBean", "classcom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1bean_1_1_mesh_log_upload_data_bean.html", null ],
    [ "com.tuya.smart.android.blemesh.api.MeshUpgradeListener", "interfacecom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1api_1_1_mesh_upgrade_listener.html", null ],
    [ "com.tuya.smart.android.device.enums.ModeEnum", "enumcom_1_1tuya_1_1smart_1_1android_1_1device_1_1enums_1_1_mode_enum.html", null ],
    [ "com.tuya.smart.android.device.bean.MultiControlDataPointsBean", "classcom_1_1tuya_1_1smart_1_1android_1_1device_1_1bean_1_1_multi_control_data_points_bean.html", null ],
    [ "com.tuya.smart.sdk.bean.MultiModeActivatorBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_multi_mode_activator_bean.html", null ],
    [ "com.tuya.smart.sdk.bean.push.TuyaPushBean.NotificationBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1push_1_1_tuya_push_bean_1_1_notification_bean.html", null ],
    [ "com.tuya.smart.android.ble.api.OnBleActivatorListener", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_on_ble_activator_listener.html", null ],
    [ "com.tuya.smart.android.ble.api.OnBleConnectListener", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_on_ble_connect_listener.html", null ],
    [ "com.tuya.smart.android.ble.api.OnBleDataTransferListener", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_on_ble_data_transfer_listener.html", null ],
    [ "com.tuya.smart.android.ble.api.OnBleIoTChannelListener", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_on_ble_io_t_channel_listener.html", null ],
    [ "com.tuya.smart.android.ble.api.OnBleMultiModeDevStatusListener", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_on_ble_multi_mode_dev_status_listener.html", null ],
    [ "com.tuya.smart.android.ble.api.OnBleRevChannelListener", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_on_ble_rev_channel_listener.html", null ],
    [ "com.tuya.smart.android.ble.api.OnBleSendChannelListener", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_on_ble_send_channel_listener.html", null ],
    [ "com.tuya.smart.android.ble.api.OnBleUpgradeListener", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_on_ble_upgrade_listener.html", null ],
    [ "com.tuya.smart.android.ble.api.OnDeviceAttributeListener", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_on_device_attribute_listener.html", null ],
    [ "com.tuya.smart.android.ble.api.OnThirdConnectListener", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_on_third_connect_listener.html", null ],
    [ "com.tuya.smart.sdk.bean.OTAErrorMessageBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_o_t_a_error_message_bean.html", null ],
    [ "com.tuya.smart.sdk.bean.cache.IDeviceProperty.OtaModuleBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1cache_1_1_i_device_property_1_1_ota_module_bean.html", null ],
    [ "com.tuya.smart.home.sdk.bean.ProductRefBean", "classcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1bean_1_1_product_ref_bean.html", null ],
    [ "com.tuya.smart.sdk.bean.ProductStandardConfig", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_product_standard_config.html", null ],
    [ "com.tuya.smart.android.push.bean.PushAlarmBean", "classcom_1_1tuya_1_1smart_1_1android_1_1push_1_1bean_1_1_push_alarm_bean.html", null ],
    [ "com.tuya.smart.sdk.api.cache.ISmartCacheManager.Relation", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1cache_1_1_i_smart_cache_manager_1_1_relation.html", null ],
    [ "com.tuya.smart.android.ble.api.ScanDeviceBean", "classcom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_scan_device_bean.html", null ],
    [ "com.tuya.smart.android.ble.api.ScanType", "enumcom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_scan_type.html", null ],
    [ "com.tuya.smart.sdk.bean.ProductBean.SchemaInfo", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_product_bean_1_1_schema_info.html", null ],
    [ "com.tuya.smart.home.sdk.utils.SchemaMapper", "classcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1utils_1_1_schema_mapper.html", null ],
    [ "com.tuya.smart.android.blemesh.builder.SearchBuilder", "classcom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1builder_1_1_search_builder.html", null ],
    [ "com.tuya.smart.home.sdk.bean.ShareInfoFromDevBean", "classcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1bean_1_1_share_info_from_dev_bean.html", null ],
    [ "com.tuya.smart.sdk.bean.ShortCutBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_short_cut_bean.html", null ],
    [ "com.tuya.smart.sdk.bean.SpeechTTSBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_speech_t_t_s_bean.html", null ],
    [ "com.tuya.smart.sdk.bean.StandSchema", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_stand_schema.html", null ],
    [ "com.tuya.smart.sdk.bean.ProductStandardConfig.StatusSchemaBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_product_standard_config_1_1_status_schema_bean.html", null ],
    [ "com.tuya.smart.sdk.bean.StandSchema.StatusSchemaListBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_stand_schema_1_1_status_schema_list_bean.html", null ],
    [ "com.tuya.smart.sdk.enums.TempUnitEnum", "enumcom_1_1tuya_1_1smart_1_1sdk_1_1enums_1_1_temp_unit_enum.html", null ],
    [ "com.tuya.smart.android.ble.api.ThirdBleScanDeviceBuilder", "classcom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_third_ble_scan_device_builder.html", null ],
    [ "com.tuya.smart.sdk.bean.Timer", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_timer.html", null ],
    [ "com.tuya.smart.sdk.bean.TimerControlBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_timer_control_bean.html", null ],
    [ "com.tuya.smart.sdk.bean.TimerControlBean.TimerControlBuilder", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_timer_control_bean_1_1_timer_control_builder.html", null ],
    [ "com.tuya.smart.android.device.enums.TimerDeviceTypeEnum", "enumcom_1_1tuya_1_1smart_1_1android_1_1device_1_1enums_1_1_timer_device_type_enum.html", null ],
    [ "com.tuya.smart.sdk.bean.TimerTask", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_timer_task.html", null ],
    [ "com.tuya.smart.sdk.bean.TimerTaskStatus", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_timer_task_status.html", null ],
    [ "com.tuya.smart.home.sdk.constant.TimerTypeEnum", "enumcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1constant_1_1_timer_type_enum.html", null ],
    [ "com.tuya.smart.home.sdk.constant.TimerUpdateEnum", "enumcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1constant_1_1_timer_update_enum.html", null ],
    [ "com.tuya.smart.home.sdk.bean.TransferDataBean", "classcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1bean_1_1_transfer_data_bean.html", null ],
    [ "com.tuya.smart.home.sdk.builder.TuyaAutoConfigActivatorBuilder", "classcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1builder_1_1_tuya_auto_config_activator_builder.html", null ],
    [ "com.tuya.smart.android.blemesh.builder.TuyaBlueMeshActivatorBuilder", "classcom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1builder_1_1_tuya_blue_mesh_activator_builder.html", null ],
    [ "com.tuya.smart.android.blemesh.builder.TuyaBlueMeshOtaBuilder", "classcom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1builder_1_1_tuya_blue_mesh_ota_builder.html", null ],
    [ "com.tuya.smart.home.sdk.builder.TuyaCameraActivatorBuilder", "classcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1builder_1_1_tuya_camera_activator_builder.html", null ],
    [ "com.tuya.smart.home.sdk.builder.TuyaGwActivatorBuilder", "classcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1builder_1_1_tuya_gw_activator_builder.html", null ],
    [ "com.tuya.smart.home.sdk.builder.TuyaGwSubDevActivatorBuilder", "classcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1builder_1_1_tuya_gw_sub_dev_activator_builder.html", null ],
    [ "com.tuya.smart.home.sdk.builder.TuyaLightningDevActivatorBuilder", "classcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1builder_1_1_tuya_lightning_dev_activator_builder.html", null ],
    [ "com.tuya.smart.sdk.bean.push.TuyaPushBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1push_1_1_tuya_push_bean.html", null ],
    [ "com.tuya.smart.home.sdk.builder.TuyaQRCodeActivatorBuilder", "classcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1builder_1_1_tuya_q_r_code_activator_builder.html", null ],
    [ "com.tuya.smart.android.blemesh.builder.TuyaSigMeshActivatorBuilder", "classcom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1builder_1_1_tuya_sig_mesh_activator_builder.html", null ],
    [ "com.tuya.smart.android.device.builder.TuyaTimerBuilder", "classcom_1_1tuya_1_1smart_1_1android_1_1device_1_1builder_1_1_tuya_timer_builder.html", null ],
    [ "com.tuya.smart.android.ble.api.TyBleScanResponse", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_ty_ble_scan_response.html", [
      [ "com.tuya.smart.android.ble.api.TuyaBleScanResponse", "interfacecom_1_1tuya_1_1smart_1_1android_1_1ble_1_1api_1_1_tuya_ble_scan_response.html", null ]
    ] ],
    [ "com.tuya.smart.sdk.enums.TYDevicePublishModeEnum", "enumcom_1_1tuya_1_1smart_1_1sdk_1_1enums_1_1_t_y_device_publish_mode_enum.html", null ],
    [ "com.tuya.smart.sdk.bean.UiInfo", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_ui_info.html", null ],
    [ "com.tuya.smart.home.sdk.callback.ITuyaDeviceUpgradeStatusCallback.UpgradeStatusEnum", "enumcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1callback_1_1_i_tuya_device_upgrade_status_callback_1_1_upgrade_status_enum.html", null ],
    [ "com.tuya.smart.home.sdk.bean.WarnMessageBean", "classcom_1_1tuya_1_1smart_1_1home_1_1sdk_1_1bean_1_1_warn_message_bean.html", null ],
    [ "com.tuya.smart.sdk.api.WifiSignalListener", "interfacecom_1_1tuya_1_1smart_1_1sdk_1_1api_1_1_wifi_signal_listener.html", null ],
    [ "com.tuya.smart.sdk.bean.ZigbeeGroupCreateResultBean", "classcom_1_1tuya_1_1smart_1_1sdk_1_1bean_1_1_zigbee_group_create_result_bean.html", null ],
    [ "Parcelable", null, [
      [ "com.tuya.smart.android.blemesh.bean.SearchDeviceBean", "classcom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1bean_1_1_search_device_bean.html", null ],
      [ "com.tuya.smart.android.device.bean.AlarmTimerBean", "classcom_1_1tuya_1_1smart_1_1android_1_1device_1_1bean_1_1_alarm_timer_bean.html", null ],
      [ "com.tuya.smart.android.device.bean.DevLocationBean", "classcom_1_1tuya_1_1smart_1_1android_1_1device_1_1bean_1_1_dev_location_bean.html", null ],
      [ "com.tuya.smart.android.user.bean.Domain", "classcom_1_1tuya_1_1smart_1_1android_1_1user_1_1bean_1_1_domain.html", null ],
      [ "com.tuya.smart.android.user.bean.User", "classcom_1_1tuya_1_1smart_1_1android_1_1user_1_1bean_1_1_user.html", null ],
      [ "com.tuya.smart.android.user.bean.UserToB", "classcom_1_1tuya_1_1smart_1_1android_1_1user_1_1bean_1_1_user_to_b.html", null ]
    ] ],
    [ "Serializable", null, [
      [ "com.tuya.smart.android.device.bean.BitmapSchemaBean", "classcom_1_1tuya_1_1smart_1_1android_1_1device_1_1bean_1_1_bitmap_schema_bean.html", null ],
      [ "com.tuya.smart.android.device.bean.BoolSchemaBean", "classcom_1_1tuya_1_1smart_1_1android_1_1device_1_1bean_1_1_bool_schema_bean.html", null ],
      [ "com.tuya.smart.android.device.bean.EnumSchemaBean", "classcom_1_1tuya_1_1smart_1_1android_1_1device_1_1bean_1_1_enum_schema_bean.html", null ],
      [ "com.tuya.smart.android.device.bean.SchemaBean", "classcom_1_1tuya_1_1smart_1_1android_1_1device_1_1bean_1_1_schema_bean.html", null ],
      [ "com.tuya.smart.android.device.bean.StringSchemaBean", "classcom_1_1tuya_1_1smart_1_1android_1_1device_1_1bean_1_1_string_schema_bean.html", null ],
      [ "com.tuya.smart.android.device.bean.UpgradeInfoBean", "classcom_1_1tuya_1_1smart_1_1android_1_1device_1_1bean_1_1_upgrade_info_bean.html", [
        [ "com.tuya.smart.android.blemesh.bean.BLEUpgradeBean", "classcom_1_1tuya_1_1smart_1_1android_1_1blemesh_1_1bean_1_1_b_l_e_upgrade_bean.html", null ]
      ] ],
      [ "com.tuya.smart.android.device.bean.ValueSchemaBean", "classcom_1_1tuya_1_1smart_1_1android_1_1device_1_1bean_1_1_value_schema_bean.html", null ],
      [ "com.tuya.smart.android.user.bean.Region", "classcom_1_1tuya_1_1smart_1_1android_1_1user_1_1bean_1_1_region.html", null ],
      [ "com.tuya.smart.android.user.bean.Region.Server", "classcom_1_1tuya_1_1smart_1_1android_1_1user_1_1bean_1_1_region_1_1_server.html", null ]
    ] ]
];